### ISSUE TITLE
Reporte de Libreria DLL

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-carlos-chrs#2]
[Reporte_Practica2_Librerias_DLL_Hernandez_Matra_carlos_Christian.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-carlos-chrs/files/6359206/Reporte_Practica2_Librerias_DLL_Hernandez_Matra_carlos_Christian.pdf)

**Comment by Edwin38H** [comment]
cal. 20

buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
